// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdwbciqilbipxigewmdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkd2JjaXFpbGJpcHhpZ2V3bWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODI0NDIsImV4cCI6MjA1OTk1ODQ0Mn0.5XRZ3Z3AC0c9B6RD7NEmnrs_djRPHVsI32dCf9IU784";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);